/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Catastro: typeof import('./src/components/Catastro.vue')['default']
    ConfirmDeleteDialog: typeof import('./src/components/comunes/ConfirmDeleteDialog.vue')['default']
    ContactFormDialog: typeof import('./src/components/comunes/ContactFormDialog.vue')['default']
    ContactTable: typeof import('./src/components/comunes/ContactTable.vue')['default']
    CrudCardData: typeof import('./src/components/commons/CrudCardData.vue')['default']
    CrudControls: typeof import('./src/components/commons/CrudControls.vue')['default']
    CrudDeleteModal: typeof import('./src/components/commons/CrudDeleteModal.vue')['default']
    CrudEditModal: typeof import('./src/components/commons/CrudEditModal.vue')['default']
    CrudTable: typeof import('./src/components/commons/CrudTable.vue')['default']
    CrudTableData: typeof import('./src/components/commons/CrudTableData.vue')['default']
    FollowUp: typeof import('./src/components/FollowUp.vue')['default']
    General: typeof import('./src/components/General.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeView: typeof import('./src/components/HomeView.vue')['default']
    PropertyMap: typeof import('./src/components/PropertyMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchAndActionsToolbar: typeof import('./src/components/comunes/SearchAndActionsToolbar.vue')['default']
    UserAgenda: typeof import('./src/components/UserAgenda.vue')['default']
    Usersprofiles: typeof import('./src/components/usersprofiles.vue')['default']
  }
}
