/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Abogados: typeof import('./src/components/especializaciones/Abogados.vue')['default']
    Ad: typeof import('./src/components/ad.vue')['default']
    AddContactDialog: typeof import('./src/components/agendautilities/AddContactDialog.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Catastro: typeof import('./src/components/Catastro.vue')['default']
    ConfirmDeleteDialog: typeof import('./src/components/comunes/ConfirmDeleteDialog.vue')['default']
    Consulta: typeof import('./src/components/Consulta.vue')['default']
    ContactAddDialog: typeof import('./src/components/comunes/ContactAddDialog.vue')['default']
    ContactAddPhoneDialog: typeof import('./src/components/comunes/ContactAddPhoneDialog.vue')['default']
    ContactCategories: typeof import('./src/components/agendautilities/ContactCategories.vue')['default']
    ContactDetails: typeof import('./src/components/agendautilities/ContactDetails.vue')['default']
    ContactDetailsModal: typeof import('./src/components/agendautilities/ContactDetailsModal.vue')['default']
    ContactEditDialog: typeof import('./src/components/comunes/ContactEditDialog.vue')['default']
    ContactFormDialog: typeof import('./src/components/comunes/ContactFormDialog.vue')['default']
    ContactInfoEditor: typeof import('./src/components/agendautilities/ContactInfoEditor.vue')['default']
    ContactTable: typeof import('./src/components/comunes/ContactTable.vue')['default']
    CrudCardData: typeof import('./src/components/commons/CrudCardData.vue')['default']
    CrudControls: typeof import('./src/components/commons/CrudControls.vue')['default']
    CrudDeleteModal: typeof import('./src/components/commons/CrudDeleteModal.vue')['default']
    CrudEditModal: typeof import('./src/components/commons/CrudEditModal.vue')['default']
    CrudTable: typeof import('./src/components/commons/CrudTable.vue')['default']
    CrudTableData: typeof import('./src/components/commons/CrudTableData.vue')['default']
    General: typeof import('./src/components/General.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeView: typeof import('./src/components/HomeView.vue')['default']
    KpiCard: typeof import('./src/components/KpiCard.vue')['default']
    Mapa: typeof import('./src/components/Mapa.vue')['default']
    Panel: typeof import('./src/components/Panel.vue')['default']
    PlanCard: typeof import('./src/components/PlanCard.vue')['default']
    PropertyMap: typeof import('./src/components/PropertyMap.vue')['default']
    Requests: typeof import('./src/components/requests.vue')['default']
    RoleGuard: typeof import('./src/components/auth/RoleGuard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchAndActionsToolbar: typeof import('./src/components/comunes/SearchAndActionsToolbar.vue')['default']
    SolicitudesSuscripcion: typeof import('./src/components/SolicitudesSuscripcion.vue')['default']
    SubscriptionRequestsManagement: typeof import('./src/components/SubscriptionRequestsManagement.vue')['default']
    SuscripcionPlanes: typeof import('./src/pages/SuscripcionPlanes.vue')['default']
    UnauthorizedSplash: typeof import('./src/components/UnauthorizedSplash.vue')['default']
    UsersManagement: typeof import('./src/components/UsersManagement.vue')['default']
    UserSplashScreen: typeof import('./src/components/UserSplashScreen.vue')['default']
    Usersprofiles: typeof import('./src/components/usersprofiles.vue')['default']
  }
}
