version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - node_modules:/app/node_modules
    env_file:
      - ./.env
    command: npm run dev
    depends_on:
      - db

  db:
    # Usa 'build' para construir la imagen desde tu Dockerfile.db
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Monta el archivo de configuración
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    shm_size: 12288mb

volumes:
  pgdata:
  node_modules: